name: build mkdocs

on:
  push:
    branches: [ main ]
  # schedule:
    # - cron:  '*/10 * * * *' # 매 10분 마다 실행한다. 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}