name: build mkdocs

on:
  push:
    branches: [ main ]
  # schedule:
    # - cron:  '*/10 * * * *' # 매 10분 마다 실행한다. 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build and deploy
      run: |
        # 바로 실행해본다. 
        mkdocs gh-deploy
    # - name: do check and notify
    #   id: check_list
    #   env:
    #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    #     APPLE_REVIEW_URL: ${{ secrets.APPLE_REVIEW_URL }}
    #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    #   run: |
    #     # 실행해보자 
    #     python ./getList.py
    # - name: git setting
    #   run: |
    #     git config --local user.email "my@email.com"
    #     git config --local user.name "깃허브액션" # 커밋에 포함될 이름
    # - name: git add tempLast file and commit
    #   if: ${{ steps.check_list.outputs.list_count > 0 }}
    #   run: |
    #     echo "숫자는? ${{ steps.check_list.outputs.list_count }} "
    #     git add tempLast.id
    #     git commit -m "자동 업데이트 진행" # 커밋 메세지
    # - name: push
    #   if: ${{ steps.check_list.outputs.list_count > 0 }}
    #   uses: ad-m/github-push-action@master
    #   with:
    #     branch: 'master'
    #     github_token: ${{ secrets.GIT_TOKEN}}